var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                    o       o     xxx           ",
   "                                           o       xx      xx    xx!!xx         ",
   "                                           xx                   xx!!!!xx        ",
   "          |                 |        o                        xxx!!!!!xxx       ",
   "          v                 v      xxxxx       o                  xvx           ",
   "                   o  =                       xxx            o              x   ",
   "  xx              xxxx                                      xxxx        o   x   ",
   "  x          o  xx    xxxx                     o                       xxx  x   ",
   "  x           xxx     xxxx     xxxx          xxxxx                          x   ",
   "  x          xxxx     xxxx                                                  x   ",
   "  x  @  o    x!!x                                                xxxxx      x   ",
   "  xxxxxxxxxxxx!!xxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxx  ",
   "                              x!!!!!!x                                          ",
   "                              x!!!!!!x                                          ",
   "                              x!!!!!!x                                          ",
   "                              xxxxxxxx                                          ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                    ",
   "                      v       v        v      v         v   v       ",
   "                                                                    ",
   "                                  o                                 ",
   "      v       v           o              o                          ",
   "                                xxxxxx                              ",
   "                 o     xxxxxx                   o                   ",
   "               xxxxxx                   xxxxx                       ",
   "            o                                             o        x",
   "    o  xxxxxx                                     xxxxx            x",
   " @                                                             =  ox",
   " xxxxxx                                                      xxxxxxx"],
  ["x   x                                                              ",
   "| @ |                                                              ",
   "|   |                    v                  v                      ",
   "|   |                                                              ",
   "|   |             o                                                ",
   "x   x                                                              ",
   "              xxxxxxxxxx                x                          ",
   "o       o                          o    x                          ",
   "xx    xxxx                              x                          ",
   "x =       x                    xxxxxxxxxx                          ",
   "                                                                   ",
   "                                                                   ",
   " xxxx                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
